name: PR Build and Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['6.0.x', '7.0.x', '8.0.x']

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: |
        dotnet restore src/Authorizer.DotNet/Authorizer.DotNet.csproj
        dotnet restore tests/Authorizer.DotNet.Tests/Authorizer.DotNet.Tests.csproj
        dotnet restore samples/Authorizer.Sample.AspNetCore/Authorizer.Sample.AspNetCore.csproj
        dotnet restore samples/Authorizer.Sample.BlazorServer/Authorizer.Sample.BlazorServer.csproj
        dotnet restore samples/Authorizer.Sample.Console/Authorizer.Sample.Console.csproj

    - name: Build
      run: |
        dotnet build src/Authorizer.DotNet/Authorizer.DotNet.csproj --no-restore --configuration Release
        dotnet build tests/Authorizer.DotNet.Tests/Authorizer.DotNet.Tests.csproj --no-restore --configuration Release
        dotnet build samples/Authorizer.Sample.AspNetCore/Authorizer.Sample.AspNetCore.csproj --no-restore --configuration Release
        dotnet build samples/Authorizer.Sample.BlazorServer/Authorizer.Sample.BlazorServer.csproj --no-restore --configuration Release
        dotnet build samples/Authorizer.Sample.Console/Authorizer.Sample.Console.csproj --no-restore --configuration Release

    - name: Test
      run: dotnet test tests/Authorizer.DotNet.Tests/Authorizer.DotNet.Tests.csproj --no-build --configuration Release --verbosity normal
